#!/usr/bin/env python3
"""Inline the 112px logo into the Worker. Run from the repo root: python3 worker/build.py"""
import base64, io, os
from PIL import Image

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.dirname(here)
im = Image.open(os.path.join(root, "assets/img/apple-touch-icon.png")).convert("RGB").resize((112, 112), Image.LANCZOS)
buf = io.BytesIO(); im.save(buf, "PNG", optimize=True)
src = open(os.path.join(here, "contact-worker.src.js")).read()
out = src.replace("__LOGO__", base64.b64encode(buf.getvalue()).decode())
open(os.path.join(here, "contact-worker.js"), "w").write("// GENERATED by worker/build.py from contact-worker.src.js. Do not edit by hand.\n" + out)
print("wrote worker/contact-worker.js", len(out))
